### ISSUE TITLE
[Tumbleweed] hibernation resume from encrypted partition no longer works

### ISSUE THREAD

**Issue by pony1k** [aplanas/dracut-pcr-signature#5]
It seems like d2d71f6f43c450d808919a8414815a24b6f77dca broke resuming from hibernation for me. I hibernate into a swap file located in my encrypted root partition, which I unlock with a passphrase. After upgrading from Tumblweed 20241102 to 20241109, this no longer works, because systemd tries to resume before the root partition has been unlocked. It then times out waiting for the root partition, resulting in this log message:
```
Nov 13 23:11:21 komputerowy systemd[1]: Timed out waiting for device /dev/disk/by-uuid/09de732f-3760-4eb8-8a7e-05abba0c67ea.
Nov 13 23:11:21 komputerowy systemd[1]: Dependency failed for Resume from hibernation.
```
I compared the the files inside the initramfs with the working and with broken resume, and the only notable difference is that the working one has a920106 and the broken one has d2d71f6f43c450d808919a8414815a24b6f77dca. I don't know much about systemd, but for me it appears like
https://github.com/aplanas/dracut-pcr-signature/blob/1ae9b3570a9fdfe9882c3800e2c486ed12f02e69/pcr-signature.service#L5-L8
results in the following ordering:
```
systemd-hibernate-resume.service
local-fs-pre.target
boot-efi.mount
pcr-signature.service
cryptsetup-pre.target
systemd-cryptsetup@cr_root.service
```
where every unit needs be started after the unit above, and that stricly orders `systemd-cryptsetup@cr_root.service` after `systemd-hibernate-resume.service`.

I do not use measured boot and the pcr-signature module was only included by default, so I could work around the issue by omitting it from my initrd. Still, this could be a problem for someone who wants measured boot and hibernation.

**Comment by aplanas** [comment]
Thanks for the report and the analysis. If you add

```
Before=systemd-hibernate-resume.service
```

does it make a difference?

**Comment by pony1k** [comment]
I haven't tried this yet, but what I tried earlier was adding a file with
```
[Unit]
After=cryptsetup.target
```
in `/etc/systemd/system/systemd-hibernate-resume.service.d/` and that resulted in
```
Nov 13 19:30:00 komputerowy systemd[1]: local-fs-pre.target: Found ordering cycle on systemd-hibernate-resume.service/start
Nov 13 19:30:00 komputerowy systemd[1]: local-fs-pre.target: Found dependency on cryptsetup.target/start
Nov 13 19:30:00 komputerowy systemd[1]: local-fs-pre.target: Found dependency on cryptsetup-pre.target/start
Nov 13 19:30:00 komputerowy systemd[1]: local-fs-pre.target: Found dependency on pcr-signature.service/start
Nov 13 19:30:00 komputerowy systemd[1]: local-fs-pre.target: Found dependency on boot-efi.mount/start
Nov 13 19:30:00 komputerowy systemd[1]: local-fs-pre.target: Found dependency on local-fs-pre.target/start
Nov 13 19:30:00 komputerowy systemd[1]: local-fs-pre.target: Job systemd-hibernate-resume.service/start deleted to break ordering cycle starting with local-fs-pre.target/start
```
I would assume that what you are proposing would create a similiar ordering cycle.
